"""add reparation_actions and action_pieces_changees tables

Revision ID: 0a7dd6e7ffbe
Revises: 5d5abfc01d76
Create Date: 2026-05-02 18:11:36.205490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7dd6e7ffbe'
down_revision = '5d5abfc01d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reparation_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparation_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technicien', sa.String(length=100), nullable=True),
    sa.Column('date_action', sa.Date(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('statut_avant', sa.String(length=20), nullable=True),
    sa.Column('statut_apres', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("statut_apres IS NULL OR statut_apres IN ('en_attente','en_reparation','pret','termine')", name='ck_action_statut_apres'),
    sa.CheckConstraint("statut_avant IS NULL OR statut_avant IN ('en_attente','en_reparation','pret','termine')", name='ck_action_statut_avant'),
    sa.CheckConstraint("type IN ('diagnostic','demontage','remplacement_piece','nettoyage','test','commentaire','statut')", name='ck_action_type'),
    sa.ForeignKeyConstraint(['reparation_id'], ['reparations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technicien_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reparation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reparation_actions_reparation_id'), ['reparation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reparation_actions_technicien_id'), ['technicien_id'], unique=False)

    op.create_table('action_pieces_changees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('piece_ref_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['reparation_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_ref_id'], ['piece_refs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_pieces_changees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_pieces_changees_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_pieces_changees_piece_ref_id'), ['piece_ref_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_pieces_changees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_pieces_changees_piece_ref_id'))
        batch_op.drop_index(batch_op.f('ix_action_pieces_changees_action_id'))

    op.drop_table('action_pieces_changees')
    with op.batch_alter_table('reparation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reparation_actions_technicien_id'))
        batch_op.drop_index(batch_op.f('ix_reparation_actions_reparation_id'))

    op.drop_table('reparation_actions')
    # ### end Alembic commands ###
