"""piece_refs_marque_id_nullable

Revision ID: 69d95788574a
Revises: 0a7dd6e7ffbe
Create Date: 2026-05-03 09:33:03.724629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d95788574a'
down_revision = '0a7dd6e7ffbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.alter_column('marque_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.alter_column('marque_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
