"""init_schema

Revision ID: cf005be22f27
Revises: 
Create Date: 2026-04-06 14:58:04.445273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf005be22f27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_type_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('type_machine', sa.String(length=100), nullable=False),
    sa.Column('url_logo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marque', 'modele', 'type_machine', name='uq_machine')
    )
    op.create_table('piece_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_piece', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_piece')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('machine_piece_refs',
    sa.Column('machine_type_id', sa.Integer(), nullable=False),
    sa.Column('piece_ref_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machine_type_refs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_ref_id'], ['piece_refs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('machine_type_id', 'piece_ref_id')
    )
    op.create_table('reparations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('machine_type', sa.String(length=200), nullable=False),
    sa.Column('technicien', sa.String(length=100), nullable=True),
    sa.Column('machine_type_id', sa.Integer(), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('date_reparation', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machine_type_refs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technicien_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reparations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reparations_machine_type_id'), ['machine_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reparations_numero_serie'), ['numero_serie'], unique=False)
        batch_op.create_index(batch_op.f('ix_reparations_technicien_id'), ['technicien_id'], unique=False)

    op.create_table('pieces_changees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparation_id', sa.Integer(), nullable=False),
    sa.Column('piece_ref_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_ref_id'], ['piece_refs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reparation_id'], ['reparations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pieces_changees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pieces_changees_piece_ref_id'), ['piece_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pieces_changees_reparation_id'), ['reparation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces_changees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pieces_changees_reparation_id'))
        batch_op.drop_index(batch_op.f('ix_pieces_changees_piece_ref_id'))

    op.drop_table('pieces_changees')
    with op.batch_alter_table('reparations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reparations_technicien_id'))
        batch_op.drop_index(batch_op.f('ix_reparations_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_reparations_machine_type_id'))

    op.drop_table('reparations')
    op.drop_table('machine_piece_refs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('piece_refs')
    op.drop_table('machine_type_refs')
    # ### end Alembic commands ###
