"""ajout statut et date_cloture sur reparations

Revision ID: a3d99c63917d
Revises: e700f9f9b350
Create Date: 2026-05-08 17:33:52.992837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d99c63917d'
down_revision = 'e700f9f9b350'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('reparations', sa.Column('date_cloture', sa.Date(), nullable=True))
    op.add_column('reparations', sa.Column('statut', sa.String(length=20), nullable=True, server_default='en_reparation'))
    op.execute("UPDATE reparations SET statut = 'en_reparation' WHERE statut IS NULL")
    op.alter_column('reparations', 'statut', nullable=False, existing_type=sa.String(length=20))
    op.create_check_constraint(
        'ck_reparation_statut',
        'reparations',
        "statut IN ('en_reparation', 'termine')"
)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reparations', schema=None) as batch_op:
        batch_op.drop_column('statut')
        batch_op.drop_column('date_cloture')

