"""initial_schema_v2

Revision ID: ca4bac96ebb9
Revises: 
Create Date: 2026-04-19 11:42:45.044362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4bac96ebb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('url_logo', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('modeles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('type_machine', sa.String(length=100), nullable=False),
    sa.Column('marque_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marque_id'], ['marques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom', 'marque_id', name='uq_modele_marque')
    )
    with op.batch_alter_table('modeles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modeles_marque_id'), ['marque_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=True)

    op.create_table('piece_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_piece', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('marque_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marque_id'], ['marques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_piece')
    )
    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piece_refs_marque_id'), ['marque_id'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('modele_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('date_entree', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("statut IN ('en_attente', 'en_reparation', 'pret', 'termine')", name='ck_machine_statut'),
    sa.ForeignKeyConstraint(['modele_id'], ['modeles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_modele_id'), ['modele_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_numero_serie'), ['numero_serie'], unique=True)

    op.create_table('modele_piece_refs',
    sa.Column('modele_id', sa.Integer(), nullable=False),
    sa.Column('piece_ref_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modele_id'], ['modeles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_ref_id'], ['piece_refs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('modele_id', 'piece_ref_id')
    )
    op.create_table('reparations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('technicien_id', sa.Integer(), nullable=True),
    sa.Column('technicien', sa.String(length=100), nullable=True),
    sa.Column('date_reparation', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technicien_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reparations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reparations_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reparations_technicien_id'), ['technicien_id'], unique=False)

    op.create_table('pieces_changees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reparation_id', sa.Integer(), nullable=False),
    sa.Column('piece_ref_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['piece_ref_id'], ['piece_refs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reparation_id'], ['reparations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pieces_changees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pieces_changees_piece_ref_id'), ['piece_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pieces_changees_reparation_id'), ['reparation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces_changees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pieces_changees_reparation_id'))
        batch_op.drop_index(batch_op.f('ix_pieces_changees_piece_ref_id'))

    op.drop_table('pieces_changees')
    with op.batch_alter_table('reparations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reparations_technicien_id'))
        batch_op.drop_index(batch_op.f('ix_reparations_machine_id'))

    op.drop_table('reparations')
    op.drop_table('modele_piece_refs')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_machines_modele_id'))

    op.drop_table('machines')
    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piece_refs_marque_id'))

    op.drop_table('piece_refs')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('modeles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modeles_marque_id'))

    op.drop_table('modeles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('marques')
    # ### end Alembic commands ###
