"""remove ActionPieceChangee

Revision ID: ddb3093b395e
Revises: a3d99c63917d
Create Date: 2026-05-09 14:42:01.859550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddb3093b395e'
down_revision = 'a3d99c63917d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_pieces_changees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_pieces_changees_action_id'))
        batch_op.drop_index(batch_op.f('ix_action_pieces_changees_piece_ref_id'))

    op.drop_table('action_pieces_changees')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('piece_refs_marque_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'marques', ['marque_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('piece_refs_marque_id_fkey'), 'marques', ['marque_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    op.create_table('action_pieces_changees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('piece_ref_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantite', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['reparation_actions.id'], name=op.f('action_pieces_changees_action_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_ref_id'], ['piece_refs.id'], name=op.f('action_pieces_changees_piece_ref_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('action_pieces_changees_pkey'))
    )
    with op.batch_alter_table('action_pieces_changees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_pieces_changees_piece_ref_id'), ['piece_ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_pieces_changees_action_id'), ['action_id'], unique=False)

    # ### end Alembic commands ###
