"""suppression champs date_entree et notes dans machine

Revision ID: e700f9f9b350
Revises: fbeae12e26b6
Create Date: 2026-05-07 18:34:00.326125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e700f9f9b350'
down_revision = 'fbeae12e26b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('date_entree')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_entree', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
