"""piece_refs_marque_id_not_null

Revision ID: fbeae12e26b6
Revises: 69d95788574a
Create Date: 2026-05-03 10:09:15.051773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbeae12e26b6'
down_revision = '69d95788574a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.alter_column('marque_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piece_refs', schema=None) as batch_op:
        batch_op.alter_column('marque_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
