upstream flask_api {
    server web:5000;
}

upstream angular_app {
    server frontend:80;
}

server {
    listen 80;
    server_name abozen.com;

    location ^~ /.well-known/acme-challenge/ {
        alias /var/www/certbot/.well-known/acme-challenge/;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name abozen.com;

    ssl_certificate /etc/letsencrypt/live/abozen.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/abozen.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    client_max_body_size 32M;

    # API Flask
    location /api/ {
        proxy_pass http://flask_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }

    # Frontend Angular (SPA — toutes les routes vers index.html)
    location / {
        proxy_pass http://angular_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }
}
